# Generated by Django 2.2.5 on 2019-10-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DefaultUserName', max_length=15)),
                ('status', models.IntegerField(default=0)),
                ('clearance', models.IntegerField(default=0)),
            ],
        ),
    ]
